# Generated by Django 5.0.3 on 2024-04-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('index', models.CharField(max_length=255)),
                ('time', models.IntegerField(default=5)),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
    ]
