# Generated by Django 5.0.3 on 2024-04-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='added_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
