# Generated by Django 5.0.3 on 2024-04-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_todo', '0003_alter_mission_added_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='remained_days',
            field=models.IntegerField(default=5),
        ),
    ]
