# Generated by Django 5.0.3 on 2024-04-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_todo', '0005_mission_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='username',
            field=models.CharField(default='non-qualified', max_length=100),
        ),
    ]
