# Generated by Django 5.0.3 on 2024-04-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_todo', '0006_alter_mission_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='username',
            field=models.CharField(default='not-edited', max_length=20),
        ),
    ]
